export SDL_EVDEV_DEVICES=2:/dev/input/event0

# SDL_EVDEV_DEVICES deviceclass:path,deviceclass:path
#    SDL_UDEV_DEVICE_UNKNOWN = 0x0000,
#    SDL_UDEV_DEVICE_MOUSE = 0x0001,
#    SDL_UDEV_DEVICE_KEYBOARD = 0x0002,
#    SDL_UDEV_DEVICE_JOYSTICK = 0x0004,
#    SDL_UDEV_DEVICE_SOUND = 0x0008,
#    SDL_UDEV_DEVICE_TOUCHSCREEN = 0x0010,
#    SDL_UDEV_DEVICE_ACCELEROMETER = 0x0020,
#    SDL_UDEV_DEVICE_TOUCHPAD = 0x0040
